### ISSUE TITLE
Consider Transformer-based language translation

### ISSUE THREAD

**Issue by GeorgeS2019** [sillsdev/machine#10]
A very interesting statistical approach to machine translation. Do consider adding additional translation module which could complement the statistical approach with **a transformer approach**.

[LANGUAGE TRANSLATION WITH NN.TRANSFORMER AND TORCHTEXT](https://pytorch.org/tutorials/beginner/translation_transformer.html)

The .NET for pytorch is supported by the Microsoft team on [Torchsharp](https://github.com/dotnet/TorchSharp)

The WIP [discussion ](https://github.com/dotnet/TorchSharp/discussions/590)how to get there

A recent pytorch approach for NMT using transformer: [sockeye](https://github.com/awslabs/sockeye)

**Comment by ddaspit** [comment]
We currently have support for inferencing from a Tensorflow NMT model that is stored as a SavedModel. Training of the model is implemented in the [Python port of Machine](https://github.com/sillsdev/machine.py/tree/main/machine/translation/tensorflow). This implemented using [OpenNMT-tf](https://github.com/OpenNMT/OpenNMT-tf). It does not support incremental training and interactive translation suggestions like the SMT model, but we hope to implement support for that in the future.

**Comment by GeorgeS2019** [comment]
@ddaspit 
For deep NLP in .NET, support for pytorch is **FAR more complete** than tensorflow.

TorchSharp's [TorchAudio: TorchAudio feasibility](https://github.com/dotnet/TorchSharp/discussions/598) is making steady progress for Text2Speech (TTS) and Speech2Text (STT).

### Language is essential to human life 
The world deserves TTS and STT that understand the native pronunciation of underrepresented populations and the rest of the world would like to hear HOW they speak in their native accents.

If your team would like to stay with .NET, which I hope, do consider TorchSharp's TorchAudio.

**Comment by johnml1135** [comment]
This is being implmented in https://github.com/sillsdev/machine.py and exposed through https://github.com/sillsdev/serval.

**Comment by GeorgeS2019** [comment]
@johnml1135 

I was hopping that you implement the translation using c#  through TorchSharp or PyTorch for .NET
e.g. https://github.com/jessiepathfinder/TinyGPT  (Transformer based GPT)

**Comment by johnml1135** [comment]
At some point in the future, maybe.  It does not match our use cases at this time.  We are training models and doing batch inferencing, because our target audience is low resource languages which are not supported by existing models.  If or when we live host the models we have trained, we may or may not use C#.
