### ISSUE TITLE
Call python from dotnet jobs for GPU python development without ClearML, all locally

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/machine#105]
A follow up to the python work began in https://github.com/sillsdev/machine/pull/101 - but left incomplete.  If we really want to use it, it needs to be fully integrated with machine.py and work in the different docker environments, especially dev.

**Comment by johnml1135** [comment]
This primarily allows the full stack to be run completely locally on a computer with a GPU without needing ClearML in one docker image.  Great for debugging! but will need some work to get seamless.

**Comment by ddaspit** [comment]
This is a duplicate of #103.
