### ISSUE TITLE
ClearML Refreshes Token too frequently

### ISSUE THREAD

**Issue by Enkidu93** [sillsdev/machine#108]
It looks like every time the health check is run, a new instance of `ClearMLAuthenticationService` is created causing Machine to repeatedly refresh the auth token. I don't think this is how it ought to work - it should be a proper singleton.

**Comment by johnml1135** [comment]
I agree - it should (ideally) be a singleton that refreshes every day (or every hour?) and when it does so, it has a few attempts if there is a failure - and allows other requests to use the old authentication until new authentication is established.
