### ISSUE TITLE
Documentation on training a new translation e.g. German to English

### ISSUE THREAD

**Issue by GeorgeS2019** [sillsdev/machine#113]
I have seen Spainish to English.

I wonder what data input format needed to do German to English?

**Comment by johnml1135** [comment]
Hello George, as per the documentation: `It is specifically focused on providing tools and techniques that are useful for processing languages that are very resource-poor.`  - and even more so, focused on Bible translation and related supports.  If you are looking for German to English, I would recommend things from Huggingface, etc.  If you are interested in using it for Bible translation for low resource languages (the other 6900 languages, not the top 100 or so), then we can help get you started with this tool or others that might be applicable to you.

**Comment by ddaspit** [comment]
You can check out the [machine translation tutorial](https://github.com/sillsdev/machine/blob/master/samples/machine_translation.ipynb). It has examples of how to train a SMT model. All you need are text files that are aligned line-by-line. You can also check out the [text corpus tutorial](https://github.com/sillsdev/machine/blob/master/samples/corpora.ipynb), which goes into more detail on how to load a parallel corpus and what formats are supported.
