### ISSUE TITLE
CMAKE_CXX_COMPILER not set, after EnableLanguage

### ISSUE THREAD

**Issue by GeoDirk** [sillsdev/machine#119]
I'm trying to compile machine on a Windows 11 ARM64 Virtual Machine running on Mac M1.  Pretty close except I'm getting these errors:

![image](https://github.com/sillsdev/machine/assets/1356726/13a3c534-7372-47b1-b0d6-771319536641)

Any idea of how and where to set the `CMAKE_CXX_COMPILER` and `CMAKE_C_COMPILER` variables?  I have CMake installed on my machine but is there any other compiler that I also need to compile this beyond the .NET stuff?

**Comment by ddaspit** [comment]
Unfortunately, Machine doesn't currently support Windows ARM64 for functionality with native dependencies. This includes the Sentencepiece tokenizer and the Thot statistical machine translation engine. I simply don't have an ARM64 system to test it on. Make sure that you have the MSVC C++ ARM64 Build Tools installed. Also, make sure that the version of CMake that you have installed supports building on ARM64.

**Comment by GeoDirk** [comment]
Hey @ddaspit 

Finally back on this and made some progress after installing the ARM64 build tools and CMAKE in Visual Studio.  The error I get now is:

```
Error	MSB3073	The command "cmake -S C:\Users\terrauser\Documents\GitHub\machine\src\SIL.Machine.Tokenization.SentencePiece\..\sentencepiece4c -B C:\Users\terrauser\Documents\GitHub\machine\src\SIL.Machine.Tokenization.SentencePiece\..\sentencepiece4c\build" exited with code 9009.	
```

Running that from the command line, I get this:

```
C:\Users\terrauser\Documents\GitHub\machine\src>cmake -S .\sentencepiece4c\ -B .\sentencepiece4c\build
-- VERSION: 0.1.96
-- Not Found TCMalloc: TCMALLOC_LIB-NOTFOUND
-- Configuring done (1.3s)
-- Generating done (0.4s)
-- Build files have been written to: C:/Users/terrauser/Documents/GitHub/machine/src/sentencepiece4c/build
```

How do I get past this step?

**Comment by ddaspit** [comment]
What is the output of running the following command?
```
cmake --build .\sentencepiece4c\build --target sentencepiece4c --config Release
```

**Comment by GeoDirk** [comment]
@ddaspit 

```
C:\Users\terrauser\Documents\GitHub\machine\src>cmake --build .\sentencepiece4c\build --target sentencepiece4c --config Release
MSBuild version 17.7.2+d6990bcfa for .NET Framework

  Checking Build System
  sentencepiece-static.vcxproj -> C:\Users\terrauser\Documents\GitHub\machine\src\sentencepiece4c\build\_deps\sentencepiece-build\src\Release\sentencepiece.lib
  sentencepiece_train-static.vcxproj -> C:\Users\terrauser\Documents\GitHub\machine\src\sentencepiece4c\build\_deps\sentencepiece-build\src\Release\sentencepiece_train.lib
  Building Custom Rule C:/Users/terrauser/Documents/GitHub/machine/src/sentencepiece4c/CMakeLists.txt
  sentencepiece4c.vcxproj -> C:\Users\terrauser\Documents\GitHub\machine\src\sentencepiece4c\bin\sentencepiece4c.dll
```

**Comment by ddaspit** [comment]
It looks like those commands are working properly. Where is it failing?

**Comment by GeoDirk** [comment]
@ddaspit 

At the end of a build for the SentencePiece project, I get this:

```
Error	MSB3073	The command "cmake -S C:\Users\terrauser\Documents\GitHub\machine\src\SIL.Machine.Tokenization.SentencePiece\..\sentencepiece4c -B C:\Users\terrauser\Documents\GitHub\machine\src\SIL.Machine.Tokenization.SentencePiece\..\sentencepiece4c\build" exited with code 9009.	
```

And the build won't go further.  When I hand run that from the console:

`cmake -S .\sentencepiece4c\ -B .\sentencepiece4c\build`

I get the error (see few messages above above for full dump):

```
-- Not Found TCMalloc: TCMALLOC_LIB-NOTFOUND
```

**Comment by ddaspit** [comment]
That is a normal message to receive when building on Windows. TCMalloc is only available on Linux. Sentencepiece can build without it. There must be something else causing the error. Delete the `build` and `bin` directories in `sentencepiece4c`, rebuild the `SIL.Machine.Tokenization.SentencePiece` project, and post the build log.

**Comment by GeoDirk** [comment]
With the TCMalloc read-herring out of the way, the build error was caused by Visual Studio not being able to find cmake.exe.  After adding that to the path, a restart of Visual Studio, I got a full build completed!

Thanks so much @ddaspit !

Feel free to close this issue after readying.
