### ISSUE TITLE
Update version number of server projects to match docker container version

### ISSUE THREAD

**Issue by ddaspit** [sillsdev/machine#122]
The version of the server projects currently match the version of number of the NuGet packages. The server projects should be versioned separately and use the same version as the docker images.

**Comment by johnml1135** [comment]
And we should document this in the readme - that there are really 2 separate things here, a package to install in your software and a web server.

**Comment by johnml1135** [comment]
In looking again, the server projects have no version.  This may be just fine - controlling version by (1) docker tags in git and (2) deployment version numbers in k8s templates.  @ddaspit what do you think?

**Comment by ddaspit** [comment]
Yes, I think this is fine for now. In the future, we might want Serval to report the version of all of the different components in the deployment. We can revisit this if we ever decide to do that.

**Comment by johnml1135** [comment]
Versioning has been updated as much as it will be for now.
