### ISSUE TITLE
SMT build error

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/machine#130]
This SMT build faulted in ext-QA.
```
\x1b[41m\x1b[30mfail\x1b[39m\x1b[22m\x1b[49m: Grpc.AspNetCore.Server.ServerCallHandler[6]
      Error when executing service method 'GetWordGraph'.
      System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at SIL.Machine.Utils.ObjectPool`1.GetAsync(CancellationToken cancellationToken) in /app/src/SIL.Machine/Utils/ObjectPool.cs:line 56
         at SIL.Machine.Translation.Thot.ThotSmtModel.GetWordGraphAsync(String segment, CancellationToken cancellationToken) in /app/src/SIL.Machine.Translation.Thot/ThotSmtModel.cs:line 120
         at SIL.Machine.Translation.HybridTranslationEngine.GetWordGraphAsync(String segment, CancellationToken cancellationToken) in /app/src/SIL.Machine/Translation/HybridTranslationEngine.cs:line 208
         at SIL.Machine.AspNetCore.Services.SmtTransferEngineService.GetWordGraphAsync(String engineId, String segment, CancellationToken cancellationToken) in /app/src/SIL.Machine.AspNetCore/Services/SmtTransferEngineService.cs:line 127

\x1b[41m\x1b[30mfail\x1b[39m\x1b[22m\x1b[49m: SIL.Machine.AspNetCore.Services.ClearMLMonitorService[0]
      Build faulted (6545d4793627520aa516b7eb). Error: ValueError : Task object can only be updated if created or in_progress [status=stopped fields=['hyperparams']]
```

What is going on here?

**Comment by Enkidu93** [comment]
I think this is a duplicate (in the first part) of https://github.com/sillsdev/serval/issues/81. Not sure why that would trigger an issue with the ClearMLMonitorService since it should only deal with NMT jobs on ClearML.

**Comment by johnml1135** [comment]
They may be separate issues that happened at the same time.  If the first issue was fixed in late September, why is it still happening?

**Comment by Enkidu93** [comment]
OK, I see. I'll investigate the ValueError. As for the previous fix, I believe the solution was to filter exceptions on the Serval side. Would you like them to be filtered on machine as well? That might be a bit trickier.

**Comment by johnml1135** [comment]
In general, Serval should not log a "fail" for any combination of user inputs.  A "fail" means that something unexpected happened (and the total range of user inputs is by definition, expected).  It may be worthwhile to change the machine to log an "info" in this case, if it is possible.

**Comment by Enkidu93** [comment]
> In general, Serval should not log a "fail" for any combination of user inputs. A "fail" means that something unexpected happened (and the total range of user inputs is by definition, expected). It may be worthwhile to change the machine to log an "info" in this case, if it is possible.

This is a log from Machine though, right? But yes, I think I can manage to change this to an info log.

As for the ValueError, because of the nature of the error and the fact that it's something in machine.py, @ddaspit may be the best person to address it. I imagine it has something to do with the changes to the code that allow for the posting of updates to the build progress.

**Comment by ddaspit** [comment]
It looks like we are trying to use the ClearML task after it was closed.

**Comment by ddaspit** [comment]
We should probably spin off the second error into a separate issue.

**Comment by Enkidu93** [comment]
I've spun off a separate issue. I'll address the logging concern.
