### ISSUE TITLE
Get Word Graph - catastrophic failure

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/machine#131]
We called word graph and machine-engine crashed.

```
2023-11-06 09:01:09 | serval-api: 2023-11-06T09:01:09.287587063Z info: Grpc.Net.Client.Internal.GrpcCall[3]       Call failed with gRPC error status. Status code: 'Unavailable', Message: 'Error starting gRPC call. HttpRequestException: An error occurred while sending the request. IOException: The request was aborted. IOException: The response ended prematurely while waiting for the next frame from the server.'.
-- | --
  |   | 2023-11-06 09:01:09 | serval-api: 2023-11-06T09:01:09.287432009Z fail: Grpc.Net.Client.Internal.GrpcCall[6]       Error starting gRPC call.       System.Net.Http.HttpRequestException: An error occurred while sending the request.        ---> System.IO.IOException: The request was aborted.        ---> System.IO.IOException: The response ended prematurely while waiting for the next frame from the server.          at System.Net.Http.Http2Connection.<ReadFrameAsync>g__ThrowMissingFrame\|58_1()          at System.Net.Http.Http2Connection.ReadFrameAsync(Boolean initialFrame)          at System.Net.Http.Http2Connection.ProcessIncomingFramesAsync()          --- End of inner exception stack trace ---          at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)          at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()          at System.Net.Http.Http2Connection.Http2Stream.TryEnsureHeaders()          at System.Net.Http.Http2Connection.Http2Stream.ReadResponseHeadersAsync(CancellationTo
  |   | 2023-11-06 09:01:09 | serval-api: 2023-11-06T09:01:05.838346253Z info: System.Net.Http.HttpClient.SmtTransfer.ClientHandler[100]       Sending HTTP request POST http://machine-engine/serval.translation.v1.TranslationEngineApi/GetWordGraph
  |   | 2023-11-06 09:01:06 | machine-engine: 2023-11-06T09:01:02.85937085Z info: System.Net.Http.HttpClient.ClearML-NoRetry.LogicalHandler[101]       End processing HTTP request after 48.2537ms - 200
  |   | 2023-11-06 09:01:05 | serval-api: 2023-11-06T09:01:05.838295592Z info: System.Net.Http.HttpClient.SmtTransfer.LogicalHandler[100]       Start processing HTTP request POST http://machine-engine/serval.translation.v1.TranslationEngineApi/GetWordGraph
  |   | 2023-11-06 09:01:05 | serval-api: 2023-11-06T09:00:49.80766581Z fail: Serval.Shared.Controllers.ServiceUnavailableExceptionFilter[0]       A user tried to access an unavailable service. See health-check logs for more details.
  |   | 2023-11-06 09:01:03 | machine-engine: 2023-11-06T09:01:02.8593362Z info: System.Net.Http.HttpClient.ClearML-NoRetry.ClientHandler[101]       Received HTTP response headers after 48.1815ms - 200
```

**Comment by ddaspit** [comment]
If we can find out which project, then we can reproduce it in a dev environment.

**Comment by johnml1135** [comment]
Can we at least wrap the C++ code code in a overall try/catch to not have the unhandled seg fault, such as with https://github.com/Plaristote/segvcatch?

**Comment by ddaspit** [comment]
Once a segmentation fault occurs, any further execution of code in the process has undefined behavior. There just isn't a safe way to continue running the process. I'm guessing that is why the library hasn't been touched in 5 years.

**Comment by ddaspit** [comment]
I did some investigation. It looks like the SMT model is corrupted. It looks like SF crashed while the model was being written to disk. I will update Machine and Thot, so that the corrupted model is handled more gracefully. The user will need to retrain the model to fix it. Maybe SF could prompt the user to retrain the model if there is an error while inferencing?

**Comment by ddaspit** [comment]
Is this a different project? If so, can we get the engine files for it.

**Comment by johnml1135** [comment]
root@machine-engine:/var/lib/machine/engines/6539938fe73fc85d889b0ebf# df
Filesystem                                             1K-blocks     Used Available Use% Mounted on
overlay                                                 50620216 28986616  21617216  58% /
tmpfs                                                      65536        0     65536   0% /dev
tmpfs                                                    3968792        0   3968792   0% /sys/fs/cgroup
/dev/root                                               50620216 28986616  21617216  58% /etc/hosts
shm                                                        65536        0     65536   0% /dev/shm
10.43.229.8:/pvc-b6ee291e-5b16-4f7c-96b0-43dc27513253      40960        0     40960   0% /root/.aspnet/DataProtection-Keys
10.43.92.112:/pvc-fedc7170-7ef7-46cc-9f24-429c89c7b437   5074944  5058560         0 100% /var/lib/machine
10.43.83.9:/pvc-9bc7710c-7a39-40fb-9e89-8b4c918f5698     5074944   948224   4110336  19% /var/lib/serval
tmpfs                                                    2560000       12   2559988   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs                                                    3968792        0   3968792   0% /proc/acpi
tmpfs                                                    3968792        0   3968792   0% /proc/scsi
tmpfs                                                    3968792        0   3968792   0% /sys/firmware
