### ISSUE TITLE
Add health check for SMT engine disk storage

### ISSUE THREAD

**Issue by ddaspit** [sillsdev/machine#141]
There is no health check for low disk storage. If the disk storage gets too low, then SMT engines will be negatively impacted. We can use [DiskStorageHealthCheck](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.System/DiskStorageHealthCheck.cs) from the [AspNetCore.HealthChecks.System](https://www.nuget.org/packages/AspNetCore.HealthChecks.System) library.

**Comment by johnml1135** [comment]
This is done through Alerts and Prometheus.  It is currently working as of this week (the email was improperly configured).  Errors come as emails and look like this:
![image](https://github.com/sillsdev/machine/assets/13733556/da535993-9ea5-41e5-bd41-21a7e33e291a)

This needs no further action at this time.

**Comment by ddaspit** [comment]
It would be easier to just check the disk space, especially since there is already a health check library that can do it.

**Comment by johnml1135** [comment]
Ok - it will be a redundant check, but I can see the value.

**Comment by Enkidu93** [comment]
In order to use this health check, we have to reference a specific drive by string (e.g. "C://"). How will this work in containers? Is this workable, @johnml1135?

**Comment by johnml1135** [comment]
I am assuming that the main paths `/var/lib/serval` and `/var/lib/machine` would need to be monitored.  They are defined in appsettings.json:
```
  "DataFile": {
    "FilesDirectory": "/var/lib/serval/files"
  }
```

and

```
  "SmtTransferEngine": {
    "EnginesDir": "/var/lib/machine/engines"
  }
```
