### ISSUE TITLE
Sample Notebooks not available on main branch

### ISSUE THREAD

**Issue by RickBrannan** [sillsdev/machine#253]
Not sure where else to report this, but the sample notebooks linked in the primary `readme.md` are not available any more. The entire `/samples` folder appears to be gone on the main branch. 

For example: https://github.com/sillsdev/machine/blob/master/samples/tokenization.ipynb returns a 404, at least for me.

The `/samples` folder is, however, available in the `garbage_collection` branch: https://github.com/sillsdev/machine/blob/garbage_collection/samples/word_alignment.ipynb 

Can you please restore the folder, or remove the links from the primary readme?

**Comment by johnml1135** [comment]
Hello @RickBrannan - the samples have been moved to https://github.com/sillsdev/machine.py/tree/main/samples.  There are two machine repos, one in dotnet (this one) and the other in python, where the samples are moved to.

**Comment by ddaspit** [comment]
Thanks for letting us know. They were accidentally removed. I created a PR (#255) to restore them.

**Comment by ddaspit** [comment]
The notebooks have been restored.

**Comment by RickBrannan** [comment]
This is great. Thanks, everybody!
