### ISSUE TITLE
Needs Version Numbers

### ISSUE THREAD

**Issue by papeh** [sillsdev/machine#3]
in `SIL.Machine.1.0.0-build00034`, the AssemblyFileVersion for SIL.Collections.dll and SIL.Machine.dll are both `1.0.0.0` In future builds, these numbers should be updated with each build (e.g. `1.0.0.35`) to allow these DLL's to be updated by Windows patch installers (such as we are using for FieldWorks)

**Comment by johnml1135** [comment]
Closing this because it is old.  I don't know if it is relevant anymore.

**Comment by papeh** [comment]
> I don't know if this is relevant anymore

https://github.com/sillsdev/fieldworks builds patch installers that update only those DLLs whose versions have changed. If SIL.Machine releases a new version whose DLLs are still `1.0.0.0`, FieldWorks users will not get the new version. FieldWorks still releases new versions as patches, so this is still relevant.

**Comment by ddaspit** [comment]
File versions for all assemblies are updated on every NuGet release.
