### ISSUE TITLE
Support individual paratext project files, not just a zip

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/machine#31]
USFM, settings.xml and custom.vrs.  This will allow just the delta to be sent to the API and not require as much zipping/unzipping.

**Comment by johnml1135** [comment]
This will also be needed for AQUA integration - making the large text file aligned with vref.txt.

**Comment by johnml1135** [comment]
Related to this: https://github.com/sillsdev/serval/issues/174

**Comment by johnml1135** [comment]
The zipped files work just fine for now.  No need to rush this.

**Comment by Enkidu93** [comment]
Given the related issue in Serval was closed, I'm closing this.
