### ISSUE TITLE
S3 hosted machine and ClearML integration

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/machine#32]
This is an interesting endeavor - we want to move data from the hosted Machine API to the ClearML server.  S3 is the chosen solution for this and it has a few parts:
* Use the aqua-ml-data s3 bucket
* Use these naming conventions:
  *  /machine-qa
  * /machine-production
  * /machine-production/parents/parent1
  * /machine-production/jobs/<build_id>
* Use environment variables to set the path.  Use secrets (ClearML and Rancher) for S3 bucket secrets
The work that needs to be done:
* Put at least one parent on he s3 bucket
* Update machine.py to to use s3 bucket data for an experiment just like silnlp
* Update machine to understand s3 bucket data and push the right (preprocessed) text files to the correct job, and read the correct "back translation"

**Comment by johnml1135** [comment]
So, how is each job structured?  We need generic corpora (we have files that have the same name, different languages and may end up conflicting because multiple corpora are selected... 
Assume two folders: 
* S3:/jobs/<my_job_id>/src
* S3:/jobs/<my_job_id>/trg
These files are added:
* For each file in a corpus, the files are named <corpus_id>.<normal_name>.txt (already made into a txt by the time it's here)
  * Since the files mirror in each folder, that is how 
  * The text files may start with a "ID\t<sentence>" format for Bible references
* For keyterms, add files but with ".keyterm" or some such extension
* Add the config.yaml file in the root, calling out the source and target text, the keywords and the parent model.
After the whole process is done, the translated files would be at:
* S3:/jobs/<my_job_id>/translations/<normal_name>.txt
This could be built in a few stages:
- [ ] Update machine.py to use the S3 buckets
- [ ] Update machine.py to look for these specific files in this specific way
- [ ] Update machine to use s3
- [ ] Update machine to push the specific files in the specific way

**Comment by ddaspit** [comment]
Most of the job code has already been implemented. I found a bug in the .NET library that I am using to access S3. I am working on fixing that now. Once that is fixed, we just need S3 buckets to point at. Here is the current structure:

- s3://<bucket_name>/builds/<build_id>/
  - train.src.txt: source sentences from all files in all corpora
  - train.trg.txt: target sentences from all files in all corpora
  - pretranslate.src.json: source sentences to pretranslate
  - pretranslate.trg.json: pretranslated target sentences

**Comment by ddaspit** [comment]
Downloading parent models and uploading child models has not been implemented yet. Here is the planned structure:

- s3://<bucket_name>/parent_models/<lang>/: parent model for target language <lang>
- s3://<bucket_name>/models/<engine_id>/: child model for engine <engine_id>

**Comment by johnml1135** [comment]
So, to get the secrets, etc. for machine and machine.py, would we do this?:
* For Machine, use [Rancher secrets](https://rancher.com/docs/rancher/v2.5/en/k8s-in-rancher/secrets/) and pull it into a configuration file as environment variables
* For Machine.py, we should be able to use user based secrets.  But then we would also need to register the clearml user in machine with Rancher secrets as well.
Does this match your understanding?
