### ISSUE TITLE
New engine type - NmtSmall

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/machine#40]
New engine type for doing an Nmt model, but the absolute smallest one we can find - that trains in < 1 hour.

**Comment by johnml1135** [comment]
This is for testing and validation, not for use.  Also, make the iterations fewer!

**Comment by johnml1135** [comment]
https://huggingface.co/prajjwal1/bert-tiny?
https://huggingface.co/bert-base-uncased?

**Comment by johnml1135** [comment]
This is based upon the capabilities addes though https://github.com/sillsdev/serval/issues/45.

**Comment by johnml1135** [comment]
This may also just be to use the full model and only train on 20 steps.

**Comment by ddaspit** [comment]
We could just make the number of steps configurable.

**Comment by johnml1135** [comment]
@ddaspit I think that would probably work - the only question is would there be value in a smaller model (100M params?) with no pretraining?  If we can't think of one, lets just have steps be configurable in the YAML file, or called out with "NLLB-200-quicktest" or "NLLB-200 --max-steps=10" etc.
