### ISSUE TITLE
Unable to load shared library 'libdl.so' or one of its dependencies

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/machine#42]
This is related to running on SIL.WritingSystems and running on Ubuntu 22.x.
See https://stackoverflow.com/questions/75855053/how-to-address-crash-due-to-missing-libdl-so-on-ubuntu-22
See https://github.com/sillsdev/libpalaso/pull/1250

**Comment by johnml1135** [comment]
This actually is not complete - but needs this one to resolve first: https://github.com/sillsdev/icu-dotnet/issues/186

**Comment by ddaspit** [comment]
@johnml1135 Is this resolved now?

**Comment by johnml1135** [comment]
This has been resolved in docker.
