### ISSUE TITLE
Race condition when creating a distributed lock

### ISSUE THREAD

**Issue by ddaspit** [sillsdev/machine#54]
[When a distributed lock is created](https://github.com/sillsdev/machine/blob/2ce24ee54d86afcd9ca0e527cce713000852f2d6/src/SIL.Machine.AspNetCore/Services/DistributedReaderWriterLock.cs#L104C35-L104C35), it checks if the lock exists prior to creating it. This is not an atomic operation and can cause a race condition that results in a crash. It would be better to attempt to insert the lock doc and catch the exception if it already exists. This can be done once in the `DistributedReaderWriterLockFactory.Create()` method.

**Comment by johnml1135** [comment]
Thanks for catching this.  It should be fixed now.
