### ISSUE TITLE
Task to listen for canceled jobs is not properly stopped when job finishes

### ISSUE THREAD

**Issue by ddaspit** [sillsdev/machine#55]
When an engine job is started, it spawns a task/thread to listen for changes to the engine. The task is not stopped when the job finishes, which results in a memory leak. The number of tasks grow indefinitely putting more and more load on the Mongo database.

**Comment by ddaspit** [comment]
This is most likely this issue: https://github.com/sillsdev/serval/issues/84.

**Comment by johnml1135** [comment]
Really nice find.  I added a "using" and also a check for the build state being "None".  I believe that should be sufficient.

**Comment by ddaspit** [comment]
Yes, that would probably be sufficient, but the code should really be refactored further to ensure that the task is finished and everything has been properly disposed when the job completes. I will add a commit to the branch that adds the necessary changes.
