### ISSUE TITLE
Refine S3 bucket usage

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/machine#61]
A collection of comments
* When the stream buffer is opened, it uses 100MB.  3 are opened at the same time per ClearML job while uploading files.  This should be ok - but with 8 going at the same time - that is 2.4 GB - a bit much.  Can we:
  * Have "WriteFilesAsync" be only opened once at time?
  * Should we use the low level implementation?
  * Throw more memory at  it - now at 2.5 GB.

**Comment by Enkidu93** [comment]
Fixed in https://github.com/sillsdev/machine/pull/80
