### ISSUE TITLE
Cancellation token - inconsistent SMT training state

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/machine#62]
As per damien:

https://github.com/sillsdev/machine/blob/2e10e0cd4a236c8479ef662154410c5a1f404315/src/SIL.Machine.AspNetCore/Services/SmtTransferEngineBuildJob.cs#L99

Cancellation tokens should not be passed to any calls after this line. It can result in an inconsistent model state.

@ddaspit can you clarify?  If we don't throw in the main for loop (below), how will we cancel in the middle of a job?

https://github.com/sillsdev/machine/blob/2e10e0cd4a236c8479ef662154410c5a1f404315/src/SIL.Machine.AspNetCore/Services/SmtTransferEngineBuildJob.cs#L117-L124

**Comment by ddaspit** [comment]
After a job has finished training and started saving the updated models, we cannot cancel. If we do, the engine will be in an inconsistent state. Most of the job has already completed at that point, so it isn't long before the job is finished.

**Comment by Enkidu93** [comment]
@ddaspit Is this all you wanted? https://github.com/sillsdev/machine/commit/d4355d71feb9445c2e2a223081c6b588839c9bbc

**Comment by Enkidu93** [comment]
Sorry, just opened a PR.
