### ISSUE TITLE
S3 remove sync write (async only)

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/machine#64]
From @ddaspit's review:

Calling async methods from a synchronous method is not safe unless you are very careful. Since the S3 SDK doesn't provide synchronous implementations of their methods, I think it would be better to not provide an implementation for the Write method. I don't think we need it. We can simply throw a NotSupportedException.

https://github.com/sillsdev/machine/blob/2e10e0cd4a236c8479ef662154410c5a1f404315/src/SIL.Machine.AspNetCore/Services/S3WriteStream.cs#L42-L54

@ddaspit - is this called anywhere?  It is used to Initialize a BufferedStream which has a sync write - we would just need to be careful to not use it - and to have the other in-memory and local drive implementations not include a sync write/read.

**Comment by Enkidu93** [comment]
Fixed in https://github.com/sillsdev/machine/pull/80
