### ISSUE TITLE
ClearML server is down - and then hangfire crashes

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/machine#65]
From this issue - https://github.com/sillsdev/machine/issues/50.  This issue is for catching the exception to not crash Hangfire.

**Comment by johnml1135** [comment]
@Enkidu93 This may help for how best to handle the exception:  https://docs.hangfire.io/en/latest/background-processing/dealing-with-exceptions.html

**Comment by Enkidu93** [comment]
Fixed with https://github.com/sillsdev/machine/pull/66
