### ISSUE TITLE
Failure - paratext backup settings file

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/machine#77]
From this error:
```
Value: [ var='B0' metric='{app="machine-job", container="machine-job", container_id="46f655e7e06d58a24c56db4bd52291042a698781f49ea1ce236e8728381d3bcd", host="kb3", log="\x1b[41m\x1b[30mfail\x1b[39m\x1b[22m\x1b[49m: SIL.Machine.AspNetCore.Services.ClearMLNmtEngineBuildJob[0]
      Build faulted (64f9faa3304d4eb4f261a899) because of exception ArgumentException:The project backup does not contain a settings file. (Parameter 'fileName').
      System.ArgumentException: The project backup does not contain a settings file. (Parameter 'fileName')
         at SIL.Machine.Corpora.ParatextBackupTextCorpus..ctor(String fileName, Boolean includeMarkers) in /app/src/SIL.Machine/Corpora/ParatextBackupTextCorpus.cs:line 25
         at SIL.Machine.AspNetCore.Services.CorpusService.CreateTextCorpus(IReadOnlyList`1 files) in /app/src/SIL.Machine.AspNetCore/Services/CorpusService.cs:line 8
         at SIL.Machine.AspNetCore.Services.ClearMLNmtEngineBuildJob.<>c__DisplayClass9_0.<g__ProcessRowsAsync|0>d.MoveNext() in /app/src/SIL.Machine.AspNetCore/Services/ClearMLNmtEngineBuildJob.cs:line 261
      --- End of stack trace from previous location ---
         at SIL.Machine.AspNetCore.Services.ClearMLNmtEngineBuildJob.<>c__DisplayClass9_0.
```

What is causing this?

**Comment by ddaspit** [comment]
The Paratext backup doesn't contain a settings file, which means that it probably isn't a project backup. More likely it is just zipped up USFM files.

**Comment by johnml1135** [comment]
So, is failing the build and giving the error which is clear enough?  Is there any meaningful way to proceed without the Settings file?

**Comment by ddaspit** [comment]
Not really. It contains metadata that is necessary to properly interpret the USFM files. I guess we could use some kind of default settings file, but this could result in all sorts of weird issues if the defaults aren't correct.

**Comment by ddaspit** [comment]
This feature is intended to be used with Paratext backup files that are generated by Paratext. To create a backup, click on the menu button and navigate to "Paratext/Advanced/Backup project to file...".

**Comment by johnml1135** [comment]
We should update the swagger documentation on paratext projects with at least these two things:
* How to create a paratext backup (as per damien's instructions)
* What it contains (a zipped file with a settings.xml, a bunch of USFM files, a custom.vrs file (if applicable) and all of them as a zipped collection of files, not a zipped folder.
