### ISSUE TITLE
Machine S3 health - warn on 1 missing, fail on >86 seconds down?

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/machine#84]
S3 buckets only claim 99.9% uptime - which is down around 86 seconds down per day.  Now, a few things that I can foresee:
1) All S3 communication is long-running and can wait for a few minutes without hurting anything
2) We should be able to live with down time of at least 86 contiguous seconds (0.1% of the day) without erroring out any jobs - gracefully retry for at least that long (90 seconds?  2 minutes?  5 minutes?)
3) While we can start giving "warning" logs and health check failures the S3 bucket is down for a few seconds, we should only start registering "failures" in the log (which sends alerts to Google chat) if it is down for over 86 seconds (or 90 seconds?  or 2 minutes?  or 5 minutes?) to not spam Google chat.

**Comment by Enkidu93** [comment]
I have something working locally. Do we want something similar for ClearML?

**Comment by Enkidu93** [comment]
> I have something working locally. Do we want something similar for ClearML?

The fix above also partially addresses any similar issues with ClearML. I don't know about our specific plan so I'm not sure what the guaranteed availability is, but I imagine this should be sufficient. To avoid missing information about timing, I could add a retry mechanic to the `ClearMLHealthCheck` so we get warning logs sooner than the error every 4 minutes (like I did with S3). Let me know if that would be helpful.

**Comment by ddaspit** [comment]
A retry policy seems like a good idea.

**Comment by Enkidu93** [comment]
Fixed [here](https://github.com/sillsdev/machine/pull/85).
