### ISSUE TITLE
Make ParallelTextCorpus more robust across different versifications

### ISSUE THREAD

**Issue by Enkidu93** [sillsdev/machine#96]
See [this](https://github.com/sillsdev/machine/pull/94#pullrequestreview-1649826748).

**Comment by ddaspit** [comment]
This hasn't been done yet.

**Comment by johnml1135** [comment]
@ddaspit  - do you know the specific changes that need to be made to accomplish this?  Doesn't this already happen?

**Comment by Enkidu93** [comment]
As I recall, basically, we need to move the logic that was previously  in the `ClearMLBuildJob` to the corpus itself.

**Comment by johnml1135** [comment]
@Enkidu93 - has this been completed yet?

**Comment by Enkidu93** [comment]
> @Enkidu93 - has this been completed yet?

My apologies for not seeing this. No, I don't believe it has. Would you like me to make this a priority? This is basically a refactoring for the sake of keeping logic in the place where it fits better semantically. The system is currently robust - it's just that the logic is in the Nmt job class rather than the parallel corpus class.
